name: Workflow Notifications

on:
  workflow_run:
    workflows: [ "cd" ]

jobs:
  notifications:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: octogeeks/send-workflow-notifications@v1
      with:
        smtp-server: "smtp.hostinger.com"
        smtp-user: "pertanian@inotive.id"
        smtp-password: "!12345Pertanian"
        configuration: ./.github/workflow-notifications.yml