name: cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 82.180.152.243
          username: "u392186142"
          password: "!12345Inotive"
          port: 22
          script: |
            cd domains/inotive.id/public_html/pertanian/
            git pull origin main